// Generated by https://quicktype.io

export interface LoginResponse {
    _id:      string;
    avatar:   string;
    banner:   string;
    email:    string;
    lastName: string;
    name:     string;
    token:    string;
    username: string;
    googleId?: string;
}
